openapi: 3.1.0
info:
  title: ddd-workshop
  version: '1.0'
servers:
  - url: 'http://ddd-workshop/api/v1'
    description: ''
paths:
  /posts:
    parameters: []
    get:
      summary: ''
      operationId: getPosts
      responses:
        '200':
          description: OK
          headers:
            X-Total-Pages:
              schema:
                type: string
              description: The total number of pages
            X-Per-Page:
              schema:
                type: string
              description: The number of items per page
            X-Next-Page:
              schema:
                type: string
              description: The index of the next page
            X-Prev-Page:
              schema:
                type: string
              description: The index of the previous page
            X-Page:
              schema:
                type: string
              description: The index of the current page (starting at 1)
            X-Total:
              schema:
                type: string
              description: X-Total
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal Server Error
      description: Retrieve all posts
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: page number
        - schema:
            type: integer
            multipleOf: 10
            minimum: 10
          in: query
          name: per_page
          description: number of items per page
    post:
      summary: CreatePost
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: CreatePost
      description: Creates a new post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
  '/posts/{post}':
    parameters:
      - schema:
          type: string
        name: post
        in: path
        required: true
    put:
      summary: UpdatePost
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: UpdatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      description: Update a post
    delete:
      summary: DeletePost
      tags: []
      responses:
        '204':
          description: No Content
        '500':
          description: Internal Server Error
      operationId: DeletePost
      description: Delete a post
    get:
      summary: GetPost
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: GetPost
      description: Retrieve a single post
components:
  schemas:
    Post:
      title: Post
      type: object
      x-tags:
        - post
      properties:
        id:
          type: string
        title:
          type: string
          minLength: 5
          example: My first post
        content:
          type: string
          minLength: 5
        imageUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - title
